flowchart TD

Title01[First Law]
    A[Force] -->
    B(Object at rest) -->
    C[Object in motion]
    
Title02[Second Law]
    D[Motion]
    D --> |Multiply| E[Mass]
    D --> |Multiply| F[Acceleration]
    D --> |Equals| G[Force]

Title03
    H[Action] --> I[Equal and opposite Reaction]
